[mysqld]
datadir=C:/mysql_data
port=3306
skip-grant-tables
bind-address=0.0.0.0
innodb_buffer_pool_size=128M
skip-log-bin
character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci
sql_mode=NO_ENGINE_SUBSTITUTION
log_error=mysql_error.log
tmpdir=C:/mysql_tmp
max_connections=100
